import "./styles/globals.css";
import React from 'react';
import { Inter } from "next/font/google";
import QueryProvider from "./providers/QueryProvider";
const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Weather App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="pt">
      <body className={inter.className}>
        <QueryProvider>
            {children}
        </QueryProvider>
      </body>
    </html>
  );
}
